name = "hollywood101tipovacka"
pages_build_output_dir = "./dist"
compatibility_date = "2026-06-02"

[[d1_databases]]
binding = "DB"
database_name = "hollywood101tipovacka"
database_id = "b1d3354f-a67a-4a08-b746-6b46536b5222"
migrations_dir = "db/migrations"
